# coding: utf-8

"""
    HAProxy Data Plane API

    API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs.   # noqa: E501

    OpenAPI spec version: 2.7
    Contact: support@haproxy.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import dataplaneapi
from dataplaneapi.api.discovery_api import DiscoveryApi  # noqa: E501
from dataplaneapi.rest import ApiException


class TestDiscoveryApi(unittest.TestCase):
    """DiscoveryApi unit test stubs"""

    def setUp(self):
        self.api = DiscoveryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_api_endpoints(self):
        """Test case for get_api_endpoints

        Return list of root endpoints  # noqa: E501
        """
        pass

    def test_get_configuration_endpoints(self):
        """Test case for get_configuration_endpoints

        Return list of HAProxy advanced configuration endpoints  # noqa: E501
        """
        pass

    def test_get_haproxy_endpoints(self):
        """Test case for get_haproxy_endpoints

        Return list of HAProxy related endpoints  # noqa: E501
        """
        pass

    def test_get_runtime_endpoints(self):
        """Test case for get_runtime_endpoints

        Return list of HAProxy advanced runtime endpoints  # noqa: E501
        """
        pass

    def test_get_services_endpoints(self):
        """Test case for get_services_endpoints

        Return list of service endpoints  # noqa: E501
        """
        pass

    def test_get_spoe_endpoints(self):
        """Test case for get_spoe_endpoints

        Return list of HAProxy SPOE endpoints  # noqa: E501
        """
        pass

    def test_get_stats_endpoints(self):
        """Test case for get_stats_endpoints

        Return list of HAProxy stats endpoints  # noqa: E501
        """
        pass

    def test_get_storage_endpoints(self):
        """Test case for get_storage_endpoints

        Return list of HAProxy storage endpoints  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
