# coding: utf-8

"""
    HAProxy Data Plane API

    API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs.   # noqa: E501

    OpenAPI spec version: 2.7
    Contact: support@haproxy.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import dataplaneapi
from dataplaneapi.api.sites_api import SitesApi  # noqa: E501
from dataplaneapi.rest import ApiException


class TestSitesApi(unittest.TestCase):
    """SitesApi unit test stubs"""

    def setUp(self):
        self.api = SitesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_site(self):
        """Test case for create_site

        Add a site  # noqa: E501
        """
        pass

    def test_delete_site(self):
        """Test case for delete_site

        Delete a site  # noqa: E501
        """
        pass

    def test_get_site(self):
        """Test case for get_site

        Return a site  # noqa: E501
        """
        pass

    def test_get_sites(self):
        """Test case for get_sites

        Return an array of sites  # noqa: E501
        """
        pass

    def test_replace_site(self):
        """Test case for replace_site

        Replace a site  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
