# coding: utf-8

"""
    HAProxy Data Plane API

    API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs.   # noqa: E501

    OpenAPI spec version: 2.7
    Contact: support@haproxy.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import dataplaneapi
from dataplaneapi.api.log_forward_api import LogForwardApi  # noqa: E501
from dataplaneapi.rest import ApiException


class TestLogForwardApi(unittest.TestCase):
    """LogForwardApi unit test stubs"""

    def setUp(self):
        self.api = LogForwardApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_log_forward(self):
        """Test case for create_log_forward

        Add a log forward  # noqa: E501
        """
        pass

    def test_delete_log_forward(self):
        """Test case for delete_log_forward

        Delete a log forward  # noqa: E501
        """
        pass

    def test_get_log_forward(self):
        """Test case for get_log_forward

        Return a log forward  # noqa: E501
        """
        pass

    def test_get_log_forwards(self):
        """Test case for get_log_forwards

        Return an array of log forwards  # noqa: E501
        """
        pass

    def test_replace_log_forward(self):
        """Test case for replace_log_forward

        Replace a log forward  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
