# coding: utf-8

"""
    HAProxy Data Plane API

    API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs.   # noqa: E501

    OpenAPI spec version: 2.7
    Contact: support@haproxy.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import dataplaneapi
from dataplaneapi.api.process_manager_api import ProcessManagerApi  # noqa: E501
from dataplaneapi.rest import ApiException


class TestProcessManagerApi(unittest.TestCase):
    """ProcessManagerApi unit test stubs"""

    def setUp(self):
        self.api = ProcessManagerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_program(self):
        """Test case for create_program

        Add a program  # noqa: E501
        """
        pass

    def test_delete_program(self):
        """Test case for delete_program

        Delete a program  # noqa: E501
        """
        pass

    def test_get_program(self):
        """Test case for get_program

        Return a program  # noqa: E501
        """
        pass

    def test_get_programs(self):
        """Test case for get_programs

        Return an array of programs  # noqa: E501
        """
        pass

    def test_replace_program(self):
        """Test case for replace_program

        Replace a program  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
