# coding: utf-8

"""
    HAProxy Data Plane API

    API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs.   # noqa: E501

    OpenAPI spec version: 2.7
    Contact: support@haproxy.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ProcessInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'error': 'str',
        'info': 'ProcessInfoItem',
        'runtime_api': 'str'
    }

    attribute_map = {
        'error': 'error',
        'info': 'info',
        'runtime_api': 'runtimeAPI'
    }

    def __init__(self, error=None, info=None, runtime_api=None):  # noqa: E501
        """ProcessInfo - a model defined in Swagger"""  # noqa: E501
        self._error = None
        self._info = None
        self._runtime_api = None
        self.discriminator = None
        if error is not None:
            self.error = error
        if info is not None:
            self.info = info
        if runtime_api is not None:
            self.runtime_api = runtime_api

    @property
    def error(self):
        """Gets the error of this ProcessInfo.  # noqa: E501


        :return: The error of this ProcessInfo.  # noqa: E501
        :rtype: str
        """
        return self._error

    @error.setter
    def error(self, error):
        """Sets the error of this ProcessInfo.


        :param error: The error of this ProcessInfo.  # noqa: E501
        :type: str
        """

        self._error = error

    @property
    def info(self):
        """Gets the info of this ProcessInfo.  # noqa: E501


        :return: The info of this ProcessInfo.  # noqa: E501
        :rtype: ProcessInfoItem
        """
        return self._info

    @info.setter
    def info(self, info):
        """Sets the info of this ProcessInfo.


        :param info: The info of this ProcessInfo.  # noqa: E501
        :type: ProcessInfoItem
        """

        self._info = info

    @property
    def runtime_api(self):
        """Gets the runtime_api of this ProcessInfo.  # noqa: E501


        :return: The runtime_api of this ProcessInfo.  # noqa: E501
        :rtype: str
        """
        return self._runtime_api

    @runtime_api.setter
    def runtime_api(self, runtime_api):
        """Sets the runtime_api of this ProcessInfo.


        :param runtime_api: The runtime_api of this ProcessInfo.  # noqa: E501
        :type: str
        """

        self._runtime_api = runtime_api

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProcessInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProcessInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
